services:
  - type: web
    name: evolution-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production