services:
  - type: web
    name: evolution-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: WEBHOOK_URL
        fromGroup: evolution-secrets
      - key: NODE_ENV
        value: production