services:
  - type: web
    name: evolution-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: "file:./database.db"  # SQLite local ou Postgres
      - key: WA_MULTI_DEVICE
        value: "true"
      - key: WEBHOOK_URL
        value: "https://seu-n8n-url.onrender.com/webhook/whatsapp"
      - key: WEBHOOK_ENABLED
        value: "true"
      - key: WEBHOOK_RETRY
        value: "true"
      - key: LOG_LEVEL
        value: "info"
